/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum050625;

import javax.swing.JOptionPane;


public class PembayaranToko extends javax.swing.JFrame {

    /**
     * Creates new form PembayaranToko
     */
    public PembayaranToko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tokopeeps = new javax.swing.JLabel();
        namabarang = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        totalpembelian = new javax.swing.JLabel();
        cbbox = new javax.swing.JComboBox<>();
        diskon = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        totalpembayaran = new javax.swing.JLabel();
        uangpembayaran = new javax.swing.JLabel();
        uangkembalian = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txttotalpembelian = new javax.swing.JTextField();
        txtdiskon = new javax.swing.JTextField();
        txttotalpembayaran = new javax.swing.JTextField();
        txtuangpembayaran = new javax.swing.JTextField();
        txtuangkembalian = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        btnkembalian = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        tokopeeps.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        tokopeeps.setText("TOKO BARANG BAGUS");

        namabarang.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        namabarang.setText("Daftar Baju");

        jumlah.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jumlah.setText("Jumlah");

        harga.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        harga.setText("Harga");

        totalpembelian.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        totalpembelian.setText("Total Pembelian");

        cbbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Model Pakaian", "UNIQLO", "Katun Combat", "Oversize", " " }));
        cbbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbboxActionPerformed(evt);
            }
        });

        diskon.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        diskon.setText("Diskon");

        totalpembayaran.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        totalpembayaran.setText("Total Pembayaran");

        uangpembayaran.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        uangpembayaran.setText("Uang Pembayaran");

        uangkembalian.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        uangkembalian.setText("Uang Kembalian");

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        btnkembalian.setText("Hitung Kembalian");
        btnkembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembalianActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalpembelian)
                            .addComponent(namabarang))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uangkembalian)
                            .addComponent(uangpembayaran)
                            .addComponent(totalpembayaran)
                            .addComponent(diskon))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuangkembalian)
                            .addComponent(txtuangpembayaran)
                            .addComponent(txttotalpembayaran)
                            .addComponent(txtdiskon)
                            .addComponent(txttotalpembelian)
                            .addComponent(txtjumlah)
                            .addComponent(cbbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(btnhitung))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnkembalian)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(harga)
                                        .addGap(69, 69, 69)
                                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnreset)
                                    .addComponent(btnkeluar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(tokopeeps)))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namabarang)
                            .addComponent(harga)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tokopeeps)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalpembelian)
                            .addComponent(txttotalpembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diskon)
                            .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalpembayaran)
                            .addComponent(txttotalpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uangpembayaran)
                            .addComponent(txtuangpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnhitung)
                        .addGap(18, 18, 18)
                        .addComponent(btnkembalian)
                        .addGap(25, 25, 25)
                        .addComponent(btnreset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkeluar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uangkembalian)
                    .addComponent(txtuangkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(882, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbboxActionPerformed
        int brg = (int) cbbox.getSelectedIndex();
        switch(brg){
            case 1 : txtharga.setText("100000");break;
            case 2 : txtharga.setText("250000");break;
            case 3 : txtharga.setText("150000");break;
            case 4 : txtharga.setText("75000");break;
            
        }
    }//GEN-LAST:event_cbboxActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
     int harga = Integer.parseInt(txtharga.getText());
     int jumlah = Integer.parseInt(txtjumlah.getText());
     int total = harga*jumlah;
     txttotalpembelian.setText(Integer.toString(total));
     double diskon =0;
     if(total>100000)
         diskon = 0.1*total;
     
     double txtbayar =total - diskon;
     txtdiskon.setText(Double.toString(diskon));
     txttotalpembayaran.setText(Double.toString(txtbayar));
     
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnkembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembalianActionPerformed
        double uang = Double.parseDouble(txtuangpembayaran.getText());
        double total = Double.parseDouble(txttotalpembayaran.getText());
        double kembalian = 0;
        
        if(uang < total )
            JOptionPane.showMessageDialog(this,"Pitih Kamu Kurang","WARNING!",JOptionPane.INFORMATION_MESSAGE);
        else{
            double uangkembalian = uang - total;
            txtuangkembalian.setText(Double.toString(kembalian));
        }
        
    }//GEN-LAST:event_btnkembalianActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
      txtharga.setText("");
      txtjumlah.setText("");
      txttotalpembelian.setText("");
      txtdiskon.setText("");
      txttotalpembayaran.setText("");
      txtuangpembayaran.setText("");
      txtuangkembalian.setText("");
      cbbox.setSelectedIndex(0);
      
      
      
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(this,"Baa Nio Kalua", "Peringataan",
                JOptionPane.YES_NO_OPTION);
        
        if(pilihan == JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PembayaranToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PembayaranToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnkembalian;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> cbbox;
    private javax.swing.JLabel diskon;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel namabarang;
    private javax.swing.JLabel tokopeeps;
    private javax.swing.JLabel totalpembayaran;
    private javax.swing.JLabel totalpembelian;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txttotalpembayaran;
    private javax.swing.JTextField txttotalpembelian;
    private javax.swing.JTextField txtuangkembalian;
    private javax.swing.JTextField txtuangpembayaran;
    private javax.swing.JLabel uangkembalian;
    private javax.swing.JLabel uangpembayaran;
    // End of variables declaration//GEN-END:variables
}
